services:
  lambda:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "9000:9000"
    environment:
      - AWS_REGION=us-east-1
    networks:
      - observability-net

  prometheus:
    image: prom/prometheus:v2.31.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - observability-net

  jaeger:
    image: jaegertracing/all-in-one:1.28
    ports:
      - "5775:5775"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14267:14267"
      - "14268:14268"
      - "9411:9411"
    networks:
      - observability-net

  grafana:
    image: grafana/grafana:8.3.3
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - observability-net

networks:
  observability-net:
    driver: bridge